### ISSUE TITLE
Message deletion does not respect batch size limit

### ISSUE THREAD

**Issue by assaflavie** [phedny/aws-sqs-processor#2]
Given a maxNumberOfMessagesPerBatch of 10 (which is the SQS limit) and a maxNumberOfMessagesProcessing limit of 50 what happens if you process messages fast enough is that 50 messages would be accumulated and then the library tries to delete all 50 in one batch call, which fails because it does not respect the batch size limit.
The fix should probably be simply to trim the deletion candidate array according to the batch limit...

**Comment by phedny** [comment]
Thanks! Your fix is released in 1.0.2
